simplify code
programmieraffe/oer-hoernchen pull request #1
Opened 2017-10-14 11:00 UTC by otacke

Just some code simplification. Could do some beautification, too.

2017-10-20 12:21 UTC, mandrasch requested changes
Regarding line 107 - site_filter_list.push(this.value);

"site:"-operator for google is missing and must be added to the value

2017-10-20 12:21 UTC, programmieraffe commented
Nice, thank you very much for simplyfing!

2017-10-20 18:56 UTC, otacke commented
Ich war beim vereinfachen etwas gründlich ;-) Hatte übersehen, dass du nicht bloß per Hand ein join() gebaut hattest, sondern auch noch zwischendrin was eingefügt hast. Nun aber ...

2017-11-08 18:56 UTC, merged

2017-11-08 19:05 UTC, otacke commented
Woohoo! Dann kann ich ja nachlegen, wenn ich etwas Zeit finde :-)

2017-11-08 19:29 UTC, programmieraffe commented
Immer gerne & besten Dank! Ich sende Karmapunkte nach Hamburg!

@danvers bastelt ja gerade in den letzten Zügen am Multilang-Feature:
https://github.com/danvers/oer-hoernchen

Weiterhin wurde mit mitgeteilt, dass das Pop-Up (welches man erst nachträglich sieht wenn man zur Seite zurückkommt) etwas verwirrend sein kann.  Zudem wollte ich noch eine Funktion einbauen, dass bei Erreichen des Wortlimits einfach mehrere Google-Suchen generiert werden.